### PR TITLE
#61-D integer operation result is out of range ( BSEC_1.4.5.1_Generic_Release_20171214 LIB+API also affected! ) 

### PR DESCRIPTION
**Pull request by ESP32DE**
#61-D integer operation result is out of range

### CODE REVIEW

**Comment by BoschSensortec** [comment]
Hi @ESP32DE,

Thanks for the pull-request. We have added a modification in the latest release v3.5.6. Let us know if the typecast fixes the problem.

**Comment by ESP32DE** [comment]
@BoschSensortec 
hi
thank you for your reply
sry no -[ your edit version](https://github.com/BoschSensortec/BME680_driver/blob/master/bme680.c#L927) does not resolve the overflow

grafik

if you use this code like i posted instead:
```
// var4 = (INT32_C(1) << 31);
var4 = (int32_t) (1U << 31);
```
then the overflow is gone.

grafik



the expression 1<<31 represents a signed int. 
to avoid the warning, explicitly define the constant 1 as an unsigned value using the U postfix.
after this, you must then cast with **int32_t** or like you want to do with **INT32_C**

hope this helps 

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
i saw your second edit now

`var4 = (int32_t)(((uint32_t)1) << 31);
`
this ( casting)  work on same way like my (1U) suggestion

many ways to roma, i close this now and use my solution for better read and knowing what's going on with the expression and the meaning behind the scene (casting like your way is unprofessional sry my opinion) 

`var4 = (int32_t) (1U << 31);`

am happy i found an Overflow BUG in your work

;-)

**Comment by ESP32DE** [comment]
@BoschSensortec 
[you must check your released Generic_Release_20171214 lib and api too](https://ae-bst.resource.bosch.com/media/_tech/media/bsec/BSEC_1.4.5.1_Generic_Release_20171214.zip)
**the overflow is still inside**!

bme680.c#L852

grafik


grafik


so i reopen this and let it open.

https://github.com/BoschSensortec/BME680_driver/issues/22

**Comment by ESP32DE** [comment]
https://github.com/BoschSensortec/BME680_driver/commit/af22c4b636dc862913b67ee2569e41a51e0c3489#commitcomment-27677023

**Comment by ESP32DE** [comment]
see https://github.com/BoschSensortec/BME680_driver/pull/26

**Pull request closed without merging**
